"""PDF report generation using ReportLab — ported from MainBackend."""
from typing import Dict, List, Any
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER, TA_RIGHT
import json
from pathlib import Path
import io


def generate_report(analysis_results: Dict[str, Any], lang: str = "en") -> bytes:
    """Generate a comprehensive PDF compliance report.

    Args:
        analysis_results: The full analysis response dict with:
            - overallScore, documentResults, categories, alerts, resources, mappings
        lang: Language code ('en' or 'ar')

    Returns:
        PDF file bytes
    """
    # Load translations for Arabic
    translations = {}
    if lang == "ar":
        try:
            with open(Path(__file__).parent / "data/translations.json") as f:
                translations = json.load(f)
        except Exception:
            pass

    def t(text: str) -> str:
        if lang == "ar":
            translated = translations.get(text, text)
            try:
                import arabic_reshaper
                from bidi.algorithm import get_display
                return get_display(arabic_reshaper.reshape(translated))
            except Exception:
                return translated
        return text

    buffer = io.BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        topMargin=40,
        bottomMargin=40,
        leftMargin=50,
        rightMargin=50,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "ReportTitle",
        parent=styles["Heading1"],
        fontSize=22,
        spaceAfter=6,
        textColor=colors.HexColor("#0E7490"),
    )
    subtitle_style = ParagraphStyle(
        "ReportSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#6B7280"),
        spaceAfter=20,
    )
    heading_style = ParagraphStyle(
        "SectionHeading",
        parent=styles["Heading2"],
        fontSize=14,
        spaceBefore=16,
        spaceAfter=8,
        textColor=colors.HexColor("#111827"),
    )
    subheading_style = ParagraphStyle(
        "SubHeading",
        parent=styles["Heading3"],
        fontSize=11,
        spaceBefore=10,
        spaceAfter=4,
        textColor=colors.HexColor("#374151"),
    )
    normal_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=9,
        leading=13,
        textColor=colors.HexColor("#374151"),
    )
    small_style = ParagraphStyle(
        "Small",
        parent=styles["Normal"],
        fontSize=8,
        leading=11,
        textColor=colors.HexColor("#6B7280"),
    )

    story = []

    # ── Title ─────────────────────────────────────────────────
    story.append(Paragraph(t("QCB Fintech Compliance Analysis Report"), title_style))
    story.append(Paragraph(t("Generated by Compliance Sentinel AI Engine"), subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB")))
    story.append(Spacer(1, 12))

    # ── Overall Score ─────────────────────────────────────────
    overall = analysis_results.get("overallScore", 0)
    score_color = "#10B981" if overall >= 70 else "#F59E0B" if overall >= 40 else "#EF4444"

    story.append(Paragraph(t("Overall Compliance Readiness Score"), heading_style))
    story.append(Paragraph(
        f"<font color='{score_color}' size='28'><b>{overall:.1f}%</b></font>",
        ParagraphStyle("ScoreDisplay", parent=normal_style, alignment=TA_CENTER, spaceBefore=4, spaceAfter=12),
    ))

    # Rating text
    if overall >= 70:
        rating = t("GOOD — Minor improvements needed")
    elif overall >= 40:
        rating = t("NEEDS IMPROVEMENT — Several compliance gaps identified")
    else:
        rating = t("CRITICAL — Major compliance gaps must be addressed before submission")
    story.append(Paragraph(
        f"<font color='{score_color}'><b>{rating}</b></font>",
        ParagraphStyle("Rating", parent=normal_style, alignment=TA_CENTER, spaceAfter=16),
    ))

    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB")))
    story.append(Spacer(1, 8))

    # ── Per-Document Scores ───────────────────────────────────
    doc_results = analysis_results.get("documentResults", {})
    if doc_results:
        story.append(Paragraph(t("Document-Level Scores"), heading_style))

        table_data = [[
            Paragraph("<b>Document</b>", small_style),
            Paragraph("<b>File</b>", small_style),
            Paragraph("<b>Score</b>", small_style),
            Paragraph("<b>Gaps</b>", small_style),
        ]]

        for doc_type, res in doc_results.items():
            label = doc_type.replace("_", " ").title()
            sc = res.get("score", 0)
            sc_color = "#10B981" if sc >= 70 else "#F59E0B" if sc >= 40 else "#EF4444"
            gap_count = len(res.get("gaps", []))
            table_data.append([
                Paragraph(label, normal_style),
                Paragraph(res.get("filename", "—"), small_style),
                Paragraph(f"<font color='{sc_color}'><b>{sc:.1f}%</b></font>", normal_style),
                Paragraph(str(gap_count), normal_style),
            ])

        table = Table(table_data, colWidths=[140, 180, 70, 50])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#F3F4F6")),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#E5E7EB")),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ]))
        story.append(table)
        story.append(Spacer(1, 16))

    # ── Compliance Gaps by Document ───────────────────────────
    story.append(Paragraph(t("Detailed Compliance Gaps"), heading_style))

    for doc_type, res in doc_results.items():
        doc_label = doc_type.replace("_", " ").title()
        gaps = res.get("gaps", [])
        if not gaps:
            continue

        story.append(Paragraph(f"{doc_label} ({len(gaps)} gaps)", subheading_style))

        for gap in gaps:
            sev = gap.get("severity", "medium")
            sev_color = "#EF4444" if sev == "critical" else "#F59E0B" if sev == "high" else "#6B7280"
            article = gap.get("article", "N/A")

            story.append(Paragraph(
                f"<font color='{sev_color}'><b>[{sev.upper()}]</b></font> "
                f"<b>{gap.get('category', '')}</b> — Art. {article}",
                normal_style,
            ))
            story.append(Paragraph(gap.get("description", ""), small_style))

            improvement = gap.get("improvement", "")
            if improvement:
                story.append(Paragraph(
                    f"<font color='#0E7490'><b>Recommendation:</b></font> {improvement}",
                    small_style,
                ))
            story.append(Spacer(1, 6))

    # ── Annotations ───────────────────────────────────────────
    has_annotations = any(
        res.get("annotations") for res in doc_results.values()
    )
    if has_annotations:
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB")))
        story.append(Paragraph(t("Document Annotations"), heading_style))

        for doc_type, res in doc_results.items():
            anns = res.get("annotations", [])
            if not anns:
                continue
            doc_label = doc_type.replace("_", " ").title()
            story.append(Paragraph(doc_label, subheading_style))
            for text_span, explanation in anns:
                story.append(Paragraph(
                    f"<b>Issue:</b> <i>{text_span}</i>", normal_style
                ))
                story.append(Paragraph(
                    f"<font color='#DC2626'><b>Required Change:</b></font> {explanation}",
                    small_style,
                ))
                story.append(Spacer(1, 4))

    # ── Semantic Matches ──────────────────────────────────────
    has_rules = any(
        res.get("relevant_rules") for res in doc_results.values()
    )
    if has_rules:
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB")))
        story.append(Paragraph(t("AI-Matched Regulatory Rules (Vector DB)"), heading_style))
        story.append(Paragraph(
            t("The following regulatory rules were semantically matched to your documents using our AI embedding engine:"),
            small_style,
        ))
        story.append(Spacer(1, 6))

        seen_texts = set()
        for doc_type, res in doc_results.items():
            for rule in res.get("relevant_rules", [])[:5]:
                rule_text = rule.get("text", "")
                if rule_text in seen_texts:
                    continue
                seen_texts.add(rule_text)
                sim = rule.get("similarity", 0)
                source = rule.get("source", "").replace(".json", "").replace("_", " ").title()
                story.append(Paragraph(
                    f"<font color='#0E7490'><b>[{sim:.0%} match]</b></font> "
                    f"<font color='#6B7280'>({source})</font>",
                    small_style,
                ))
                story.append(Paragraph(f"<i>{rule_text[:300]}</i>", small_style))
                story.append(Spacer(1, 4))

    # ── Resources ─────────────────────────────────────────────
    resources = analysis_results.get("resources", [])
    if resources:
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB")))
        story.append(Paragraph(t("Recommended Resources & Experts"), heading_style))

        for res in resources:
            story.append(Paragraph(
                f"<b>{res['name']}</b> — <i>{res.get('type', '')}</i>",
                normal_style,
            ))
            desc = res.get("description", "")
            if desc:
                story.append(Paragraph(desc, small_style))
            contact = res.get("contact", "")
            if contact:
                story.append(Paragraph(f"Contact: {contact}", small_style))
            story.append(Spacer(1, 6))

    # ── Missing Requirements ──────────────────────────────────
    all_missing = []
    for res in doc_results.values():
        all_missing.extend(res.get("missing_requirements", []))
    if all_missing:
        story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#E5E7EB")))
        story.append(Paragraph(t("Missing Requirements Checklist"), heading_style))
        for req in list(dict.fromkeys(all_missing)):  # dedupe preserving order
            story.append(Paragraph(f"☐  {req}", normal_style))
        story.append(Spacer(1, 8))

    # ── Footer ────────────────────────────────────────────────
    story.append(Spacer(1, 20))
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#E5E7EB")))
    story.append(Paragraph(
        t("This report was generated by Compliance Sentinel AI. "
          "It is intended for internal use only and does not constitute legal advice. "
          "Please consult with QCB-authorized compliance experts for formal submissions."),
        ParagraphStyle("Footer", parent=small_style, alignment=TA_CENTER, spaceBefore=8),
    ))

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes
